---
version: 0.2

env:
  variables:
    ENV_NAME: test

phases:
  install:
    commands:
      - echo Install phase - building test setup - `date`
      - apt-get update
      - apt-get install jq
  pre_build:
    commands:
      - echo Pre-Build phase - running the test suite - `date`
      - make docker-build-clear
      - make t
  build:
    commands:
      - echo Build phase - building the rails and nginx containers - `date`
      - docker build -t pcw-rails:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker build -f Dockerfile.nginx -t pcw-nginx:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  post_build:
    commands:
      - echo Post-Build phase - tagging and uploading the images to ECR - `date`
      - $(aws ecr get-login --region us-west-2 --no-include-email)
      - >
        docker tag pcw-rails:$CODEBUILD_RESOLVED_SOURCE_VERSION
        949953444104.dkr.ecr.us-west-2.amazonaws.com/pcw-rails:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - >
        docker tag pcw-nginx:$CODEBUILD_RESOLVED_SOURCE_VERSION
        949953444104.dkr.ecr.us-west-2.amazonaws.com/pcw-nginx:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - >
        docker tag pcw-rails:$CODEBUILD_RESOLVED_SOURCE_VERSION
        949953444104.dkr.ecr.us-west-2.amazonaws.com/pcw-rails:$ENV_NAME
      - >
        docker tag pcw-nginx:$CODEBUILD_RESOLVED_SOURCE_VERSION
        949953444104.dkr.ecr.us-west-2.amazonaws.com/pcw-nginx:$ENV_NAME
      - "docker push 949953444104.dkr.ecr.us-west-2.amazonaws.com/pcw-rails"
      - "docker push 949953444104.dkr.ecr.us-west-2.amazonaws.com/pcw-nginx"

      - >
        printf '{"Parameters" : {}, "StackPolicy" :{"Statement" : [{"Effect" : "Allow", "NotAction" : "Update:Delete", "Principal": "*", "Resource" : "*"}]}}' > changeset.json
      - aws s3 cp s3://a3-templates-us-west-2/$ENV_NAME/master.yaml .
      - aws cloudformation describe-stacks --region us-west-2 --stack-name $ENV_NAME  | jq -r --arg CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_RESOLVED_SOURCE_VERSION '.Stacks[0].Parameters|.[]|select( .ParameterKey=="PCWRevision").ParameterValue= $CODEBUILD_RESOLVED_SOURCE_VERSION|to_entries|map(.value)|{ "key":.[0], "value":.[1] }'| jq -s 'from_entries'>params.json
      - jq -s '.[0].Parameters=.[1]|.[0]' changeset.json params.json > configuration.json



      - echo Build completed - `date`

artifacts:
  files:
    - configuration.json
    - master.yaml
