version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./build_and_push.sh
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
