version: '3.2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"

  pcw:
    build: .
    command: /pcw/start_server.sh
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/pcw
