version: '3.2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5437:5437"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
  pcw:
    build: .
    command: /pcw/start_server.sh
    ports:
      - "3000:3000"
    depends_on:
       - db
    links:
      - db
    volumes:
      - .:/pcw
