default: &default
  domain: <%= ENV['PCW_AUTH0_DOMAIN'] %>
  client_id: <%= ENV['PCW_AUTH0_CLIENT_ID'] %>
  client_secret: <%= ENV['PCW_AUTH0_CLIENT_SECRET'] %>
  connection: <%= ENV['PCW_AUTH0_CONNECTION'] || 'Username-Password-Authentication' %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
