default: &default
  adapter: postgresql
  encoding: unicode
  database: pcw
  host: <%= ENV['PCW_DB_HOST'] || 'db' %>
  port: 5432
  pool: 10
  username: <%= ENV['PCW_DB_USER'] || 'postgres' %>
  password: <%= ENV['PCW_DB_PASSWORD'] || nil %>
  timeout: 5000

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: pcw_test
