default: &default
  adapter: postgresql
  encoding: unicode
  database: pce
  host: pce-prd-default.cefvztdkizng.us-west-2.rds.amazonaws.com
  port: 5432
  pool: 10
  username: pce
  password: MKJqsTJ6v54q556c
  timeout: 5000

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: pcw_test