default: &default
  adapter: postgresql
  encoding: unicode
  database: pcw2
  host: postgresql
  port: 5432
  pool: 10
  username: pcw
  password: pcw
  timeout: 5000

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: pcw_test