default: &default
  auth0:
    connection: 'rocket'
    client:
      secret: "MTk2696loCTKnGC3r3eY_uZoMqByOU0WV6IB310oA1FtyIN78YvTn6gpywe38C8c"
      id: "aG4MaVo0u33LihkxarfQ9Ys5qUQPvlI0"
  domain: "stage3demo.auth0.com"
  tenant: "stage3"
  url: "https://identity-stg.stage3systems.com"
  user: "sedna"
  password: "arrabella"
  clear_token_on_logout: false

development:
  <<: *default

production:
  <<: *default