default: &default
  auth0:
    connection: 'rocket'
    client:
      secret: ''
      id: ''
  domain: ''
  tenant: ''
  url: ''
  user: ''
  password: ''
  clear_token_on_logout: false

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
