module PortsHelper

    def get_asian_ports()
        ["BANGKOK", "BONTANG", "CILACAP", "HAINAN STRAITS", "JAKARTA", "KOH SAMUI", "KOH SICHANG", "LAEM CHABANG", "LANQIAO", "MAP TA PHUT", "MEULABOH", "MUARA PANTAI", "PENGERANG", "PHUKET", "RAYONG", "RIZHAO", "RUWAIS", "SAMARINDA", "SEMARANG", "SHANGHAI", "SINGAPORE", "SRIRACHA", "SUNGAI PAKNING", "SURABAYA", "TIANJIN XIN GANG", "ZHOUSHAN", "YOSU", "BUSAN", "RAS TANURA", "KALIORANG", "MUARA SATUI", "MERAK", "BANG SAPHAN", "BUNATI", "KRABI", "TANJUNG BARA", "PADANG", "TABONEO", "TUBAN", "TANJUNG BUYUT", "TANJUNG KAMPEH", "BALIKPAPAN",
        "BANJARMASIN",
        "BATU AMPAR",
        "BELAWAN",
        "CHITTAGONG",
        "CIREBON",
        "DUMAI",
        "GRESIK",
        "MONGLA",
        "RANONG",
        "SATTAHIP",
        "TANJUNG EMAS",
        "TANJUNG INTAN",
        "TANJUNG SABAU"]
    end

    def get_australian_ports()
        ["ABBOT POINT","ADELAIDE","BELL BAY","BRISBANE","BURNIE","DALRYMPLE BAY","DAMPIER","FREMANTLE","GEELONG","GERALDTON","GLADSTONE","HAY POINT","LAUNCESTON","MACKAY","MELBOURNE","NEWCASTLE","PORT BOTANY","PORT HEDLAND","PORT KEMBLA","PORT WALCOTT","SYDNEY","TOWNSVILLE","ALBANY","BUNDABERG","DARWIN","EDEN","GOVE","GROOTE EYLANDT","HASTINGS","PORT BONYTHON","PORT GILES","PORT LATTA","PORT LINCOLN","PORT PIRIE","STAG FIELD","THEVENARD","WALLAROO","WEIPA","WESTERN PORT","WHYALLA","BUNBURY","CAIRNS","CAPE CUVIER","CAPE PRESTON","DEVONPORT","ESPERANCE","HOBART","KWINANA","LUCINDA","MOURILYAN","PORT ALMA","PORTLAND", "WELLINGTON", "TAURANGA"]
    end

    def get_png_ports()
        ["LAE","PORT MORESBY","ALOTAU","KIRIWINA","RABAUL","CONFLICT ISLAND","DOINI ISLAND","KITAVA","MADANG","BASAMUK","KIMBE"]
    end

    def get_mozambique_ports()
        ["MAPUTO", "MATOLA", "BEIRA", "NACALA", "PEMBA"]
    end

    def get_tanzania_ports()
        ["DAR ES SALAAM", "MTWARA", "TANGA", "ZANZIBAR"]
    end

    def get_namibia_ports()
        ["LUDERITZ", "WALVIS BAY"]
    end

end
