module PortsHelper

    def get_thai_ports()
        [
            "BANGKOK",
            "LAEM CHABANG",
            "MAP TA PHUT",
            "RAYONG",
            "SRIRACHA",
            "KOH SICHANG",
            "PHUKET",
            "KOH SAMUI",
            "KANTANG HARBOR",
            "RANONG",
            "BANG SAPHAN",
            "KRABI",
            "SATTAHIP"
        ]
    end

    def get_madagascar_ports()
        [
            "ANTSIRANANA",
            "MAHAJANGA",
            "TOAMASINA",
            "TAOLAGNARO",
            "EHOALA",
            "TOLIARA"
        ]
    end

    def get_asian_ports()
        ["BANGKOK", "BONTANG", "CILACAP", "HAINAN STRAITS", "JAKARTA", "KOH SAMUI", "KOH SICHANG", "LAEM CHABANG", "LANQIAO", "MAP TA PHUT", "MEULABOH", "MUARA PANTAI", "PENGERANG", "PHUKET", "RAYONG", "RIZHAO", "RUWAIS", "SAMARINDA", "SEMARANG", "SHANGHAI", "SINGAPORE", "SRIRACHA", "SUNGAI PAKNING", "SURABAYA", "TIANJIN XIN GANG", "ZHOUSHAN", "YOSU", "BUSAN", "RAS TANURA", "KALIORANG", "MUARA SATUI", "MERAK", "BANG SAPHAN", "BUNATI", "KRABI", "TANJUNG BARA", "PADANG", "TABONEO", "TUBAN", "TANJUNG BUYUT", "TANJUNG KAMPEH", "BALIKPAPAN",
        "BANJARMASIN",
        "BATU AMPAR",
        "BELAWAN",
        "CHITTAGONG",
        "CIREBON",
        "DUMAI",
        "GRESIK",
        "MONGLA",
        "RANONG",
        "SATTAHIP",
        "TANJUNG EMAS",
        "TANJUNG INTAN",
        "TANJUNG SABAU",
        "TANJUNG PELEPAS",
        "TARAHAN",
        "SATTASHIP", "BITUNG", "KENDARI", "BUNYU", "BALONGAN", "BANTONG", "PASIR GUDANG", "PORT KLANG", "TANJUNG BIN", "TANJUNG LANGSAT", "PANJANG", "CIWANDAN", "KOH PHALUAI", "BALI", "ANYER LOR", "CIGADING", "TANJUNG MANIS"]

    end

    def get_australian_ports()
        ["ABBOT POINT","ADELAIDE","BELL BAY","BRISBANE","BURNIE","DALRYMPLE BAY","DAMPIER", "DILI","FREMANTLE","GEELONG","GERALDTON","GLADSTONE","HAY POINT","LAUNCESTON","MACKAY","MELBOURNE","NEWCASTLE","PORT BOTANY","PORT HEDLAND","PORT KEMBLA","PORT WALCOTT","SYDNEY","TOWNSVILLE","ALBANY","BUNDABERG","DARWIN","EDEN","GOVE","GROOTE EYLANDT","HASTINGS","PORT BONYTHON","PORT GILES","PORT LATTA","PORT LINCOLN","PORT PIRIE","STAG FIELD","THEVENARD","WALLAROO","WEIPA","WESTERN PORT","WHYALLA","BUNBURY","CAIRNS","CAPE CUVIER","CAPE PRESTON","DEVONPORT","ESPERANCE","HOBART","KWINANA","LUCINDA","MOURILYAN","PORT ALMA","PORTLAND","WELLINGTON","TAURANGA","BLACKTIP TERMINAL","PORT AUKLAND","AUCKLAND","NEW PLYMOUTH","TIMARU","NAPIER BLUFF","MARSDEN POINT","NELSON PORT","LYTTELTON","DUNEDIN","PORT CHALMERS", "WHANGAREI", "KOOLAN ISLAND"]
    end

    def get_png_ports()
        ["LAE","PORT MORESBY","ALOTAU","KIRIWINA","RABAUL","CONFLICT ISLAND","DOINI ISLAND","KITAVA","MADANG","BASAMUK","KIMBE", "LIHIR", "WEWAK"]
    end

    def get_mozambique_ports()
        ["MAPUTO", "MATOLA", "BEIRA", "NACALA", "PEMBA"]
    end

    def get_tanzania_ports()
        ["DAR ES SALAAM", "MTWARA", "TANGA", "ZANZIBAR"]
    end

    def get_namibia_ports()
        ["LUDERITZ", "WALVIS BAY"]
    end

end
